sudo: required
language: bash
services: docker

env:
  global:
    - VERSION=2.8 IMAGE=ffmpeg
    - VERSION=3.3-vmaf IMAGE=ffmpeg

jobs:
  include:
    - stage: build, test and deploy image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/$IMAGE:latest -t $DOCKER_USERNAME/$IMAGE:$VERSION $VERSION
      - docker images
      - docker run $DOCKER_USERNAME/$IMAGE
      - docker tag $DOCKER_USERNAME/$IMAGE:latest $DOCKER_USERNAME/$IMAGE:$VERSION
      - docker push $DOCKER_USERNAME/$IMAGE:latest
      - docker push $DOCKER_USERNAME/$IMAGE:$VERSION
